development:
  adapter: postgresql
  database: academico_db
  encoding: utf8
  host: db
  port: 5432
  username: auto_academ
  password: auto_academ

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000