version: '3.7'

services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: academico_db
      POSTGRES_USER: auto_academ
      POSTGRES_PASSWORD: auto_academ
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/home/scripts
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auto_academ -d academico_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ruby:
    build: 
      context: ./off_the_rails
    depends_on:
      db:
        condition: service_healthy
    command: ruby main.rb
    volumes:
      - ./off_the_rails/app:/app

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  python:
    build:
      context: ./python
    depends_on:
      rabbitmq:
        condition: service_healthy
      ruby:
        condition: service_started
      db:
        condition: service_started
    command: python main.py
    volumes:
      - ./python/app:/app

  api:
    build: 
      context: ./api
    ports:
      - 80:80