version: '3.7'

services:
  db:
    build:
      dockerfile: Dockerfile-postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/home/scripts
    ports:
      - "5432:5432"
  ruby:
    build: 
      dockerfile: Dockerfile-ruby
    depends_on:
      - db
    command: bash -c "rake db:create && rake db:schema:load"
    volumes:
      - ./scripts/off_the_rails:/app