version: '3.7'

services:
  db:
    build:
      context: ./db
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/home/scripts
    ports:
      - "5432:5432"

  ruby:
    build: 
      context: ./off_the_rails
    depends_on:
      - db
    command: bash -c "rake db:create && rake db:schema:load"
    volumes:
      - ./off_the_rails/app:/app

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  python:
    build:
      context: ./python
    depends_on:
      - ruby
    volumes:
      - ./python/:/python